name: Validate master PR

on:
  pull_request:
    branches:
      - p1-master

jobs:
  validate-source:
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "p1-dev" ]; then
            echo "Only 'p1-dev' can merge into master."
            exit 1
          fi
